server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

cache:
  pre: NIO_IM     #缓存前缀
  sp: ':'         #缓存分隔符

dictionary:
  zodiac: zodiac  #生肖
  constellation: constellation   #星座


